name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact
                required: true
                type: string
        # secrets:
        #     some-secret:
        #         required: true
        outputs:
            result:
                value: ${{ jobs.deploy.outputs.outcome }}

jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - run: ls
            - name: set output
              id: set-result
              run: echo "step-result=Success" >> $GITHUB_OUTPUT